### ISSUE TITLE
(Fix) Redeploy for Core

### ISSUE THREAD

**Issue by igorbarinov** [poanetwork/poa-popa#11]
Problem:
Kovan is not working well https://authorities.kovan.network
Solution:
Deploy popa on Core

**Comment by phahulin** [comment]
Done.

<details>
<summary>contract-output</summary>
<pre>
{
    "ProofOfPhysicalAddress": {
        "address": "0xb73f4fd5a696b2e69d10f6afc465191e80daafbf",
        "bytecode": "6060604052341561000f57600080fd5b336000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055506000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff16600160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550613248806100c06000396000f30060606040526004361061011d576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806315b8452b1461012257806319a8176414610173578063238ac933146101ac578063316ca5cf146102015780633710b8491461046c5780633c38db251461048f57806341516e7c146104dc578063415a7f031461054c578063447f0675146105b857806369cf5bbf1461076a57806377ac2f1d146107ed5780637fcda595146109ca5780638da5cb5b14610a075780639029eb0414610a5c5780639b4a716d14610a99578063a87430ba14610b4b578063af701f2814610b98578063b6c5000c14610bf2578063dd473d2b14610cbb578063e7cc62bd14610cd0578063f517289914610d0d575b600080fd5b341561012d57600080fd5b610159600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091905050610d72565b604051808215151515815260200191505060405180910390f35b341561017e57600080fd5b6101aa600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091905050610dc0565b005b34156101b757600080fd5b6101bf610e5f565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b341561020c57600080fd5b610241600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091908035906020019091905050610e85565b60405180806020018060200180602001806020018060200186810386528b818151815260200191508051906020019080838360005b83811015610291578082015181840152602081019050610276565b50505050905090810190601f1680156102be5780820380516001836020036101000a031916815260200191505b5086810385528a818151815260200191508051906020019080838360005b838110156102f75780820151818401526020810190506102dc565b50505050905090810190601f1680156103245780820380516001836020036101000a031916815260200191505b50868103845289818151815260200191508051906020019080838360005b8381101561035d578082015181840152602081019050610342565b50505050905090810190601f16801561038a5780820380516001836020036101000a031916815260200191505b50868103835288818151815260200191508051906020019080838360005b838110156103c35780820151818401526020810190506103a8565b50505050905090810190601f1680156103f05780820380516001836020036101000a031916815260200191505b50868103825287818151815260200191508051906020019080838360005b8381101561042957808201518184015260208101905061040e565b50505050905090810190601f1680156104565780820380516001836020036101000a031916815260200191505b509a505050505050505050505060405180910390f35b341561047757600080fd5b61048d60048080359060200190919050506113c1565b005b341561049a57600080fd5b6104c6600480803573ffffffffffffffffffffffffffffffffffffffff169060200190919050506114a4565b6040518082815260200191505060405180910390f35b34156104e757600080fd5b610520600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091908035600019169060200190919050506114f3565b604051808415151515815260200183815260200182151515158152602001935050505060405180910390f35b341561055757600080fd5b61058c600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091908035906020019091905050611609565b604051808415151515815260200183815260200182151515158152602001935050505060405180910390f35b34156105c357600080fd5b61073e600480803573ffffffffffffffffffffffffffffffffffffffff1690602001909190803590602001908201803590602001908080601f0160208091040260200160405190810160405280939291908181526020018383808284378201915050505050509190803590602001908201803590602001908080601f0160208091040260200160405190810160405280939291908181526020018383808284378201915050505050509190803590602001908201803590602001908080601f0160208091040260200160405190810160405280939291908181526020018383808284378201915050505050509190803590602001908201803590602001908080601f0160208091040260200160405190810160405280939291908181526020018383808284378201915050505050509190803590602001908201803590602001908080601f01602080910402602001604051908101604052809392919081815260200183838082843782019150505050505091905050611717565b604051808415151515815260200183815260200182151515158152602001935050505060405180910390f35b341561077557600080fd5b6107eb600480803590602001908201803590602001908080601f0160208091040260200160405190810160405280939291908181526020018383808284378201915050505050509190803560ff169060200190919080356000191690602001909190803560001916906020019091905050611cf1565b005b6109c8600480803590602001908201803590602001908080601f0160208091040260200160405190810160405280939291908181526020018383808284378201915050505050509190803590602001908201803590602001908080601f0160208091040260200160405190810160405280939291908181526020018383808284378201915050505050509190803590602001908201803590602001908080601f0160208091040260200160405190810160405280939291908181526020018383808284378201915050505050509190803590602001908201803590602001908080601f0160208091040260200160405190810160405280939291908181526020018383808284378201915050505050509190803590602001908201803590602001908080601f0160208091040260200160405190810160405280939291908181526020018383808284378201915050505050509190803590602001908201803590602001908080601f016020809104026020016040519081016040528093929190818152602001838380828437820191505050505050919080359060200190919080356000191690602001909190803560ff169060200190919080356000191690602001909190803560001916906020019091905050611f31565b005b34156109d557600080fd5b6109dd612744565b604051808267ffffffffffffffff1667ffffffffffffffff16815260200191505060405180910390f35b3415610a1257600080fd5b610a1a61275e565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b3415610a6757600080fd5b610a6f612783565b604051808267ffffffffffffffff1667ffffffffffffffff16815260200191505060405180910390f35b3415610aa457600080fd5b610ad0600480803573ffffffffffffffffffffffffffffffffffffffff1690602001909190505061279d565b6040518080602001828103825283818151815260200191508051906020019080838360005b83811015610b10578082015181840152602081019050610af5565b50505050905090810190601f168015610b3d5780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b3415610b5657600080fd5b610b82600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091905050612901565b6040518082815260200191505060405180910390f35b3415610ba357600080fd5b610bd8600480803573ffffffffffffffffffffffffffffffffffffffff1690602001909190803590602001909190505061291f565b604051808215151515815260200191505060405180910390f35b3415610bfd57600080fd5b610c32600480803573ffffffffffffffffffffffffffffffffffffffff169060200190919080359060200190919050506129a1565b6040518080602001848152602001838152602001828103825285818151815260200191508051906020019080838360005b83811015610c7e578082015181840152602081019050610c63565b50505050905090810190601f168015610cab5780820380516001836020036101000a031916815260200191505b5094505050505060405180910390f35b3415610cc657600080fd5b610cce612b8b565b005b3415610cdb57600080fd5b610ce3612c85565b604051808267ffffffffffffffff1667ffffffffffffffff16815260200191505060405180910390f35b3415610d1857600080fd5b610d5860048080356000191690602001909190803560ff169060200190919080356000191690602001909190803560001916906020019091905050612c9f565b604051808215151515815260200191505060405180910390f35b600080600260008473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060000154119050919050565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16141515610e1b57600080fd5b80600160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b610e8d612fb6565b610e95612fb6565b610e9d612fb6565b610ea5612fb6565b610ead612fb6565b610eb687610d72565b1515610ec157600080fd5b600260008873ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060010186815481101515610f1057fe5b9060005260206000209060090201600101600260008973ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060010187815481101515610f7057fe5b9060005260206000209060090201600201600260008a73ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060010188815481101515610fd057fe5b9060005260206000209060090201600301600260008b73ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206001018981548110151561103057fe5b9060005260206000209060090201600401600260008c73ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206001018a81548110151561109057fe5b9060005260206000209060090201600501848054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156111365780601f1061110b57610100808354040283529160200191611136565b820191906000526020600020905b81548152906001019060200180831161111957829003601f168201915b50505050509450838054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156111d25780601f106111a7576101008083540402835291602001916111d2565b820191906000526020600020905b8154815290600101906020018083116111b557829003601f168201915b50505050509350828054600181600116156101000203166002900480601f01602080910402602001604051908101604052809291908181526020018280546001816001161561010002031660029004801561126e5780601f106112435761010080835404028352916020019161126e565b820191906000526020600020905b81548152906001019060200180831161125157829003601f168201915b50505050509250818054600181600116156101000203166002900480601f01602080910402602001604051908101604052809291908181526020018280546001816001161561010002031660029004801561130a5780601f106112df5761010080835404028352916020019161130a565b820191906000526020600020905b8154815290600101906020018083116112ed57829003601f168201915b50505050509150808054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156113a65780601f1061137b576101008083540402835291602001916113a6565b820191906000526020600020905b81548152906001019060200180831161138957829003601f168201915b50505050509050945094509450945094509295509295909350565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614151561141c57600080fd5b803073ffffffffffffffffffffffffffffffffffffffff1631101561144057600080fd5b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166108fc829081150290604051600060405180830381858888f1935050505015156114a157600080fd5b50565b6000600260008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600101805490509050919050565b60008060008061150286610d72565b151561150d57600080fd5b600090505b600260008773ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600101805490508110156115f2578460001916600260008873ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600101828154811015156115b357fe5b9060005260206000209060090201600701546000191614156115e7576001816115dc888461291f565b935093509350611601565b600181019050611512565b60008060008191509350935093505b509250925092565b60008060008061161886610d72565b151561162357600080fd5b600090505b600260008773ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600101805490508110156117005784600260008873ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600101828154811015156116c557fe5b90600052602060002090600902016006015414156116f5576001816116ea888461291f565b93509350935061170f565b600181019050611628565b60008060008191509350935093505b509250925092565b6000806000806117268a610d72565b151561173157600080fd5b600090505b600260008b73ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060010180549050811015611cd557611885600260008c73ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600101828154811015156117d557fe5b90600052602060002090600902016001018054600181600116156101000203166002900480601f01602080910402602001604051908101604052809291908181526020018280546001816001161561010002031660029004801561187a5780601f1061184f5761010080835404028352916020019161187a565b820191906000526020600020905b81548152906001019060200180831161185d57829003601f168201915b50505050508a612e3b565b801561198f575061198e600260008c73ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600101828154811015156118de57fe5b90600052602060002090600902016002018054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156119835780601f1061195857610100808354040283529160200191611983565b820191906000526020600020905b81548152906001019060200180831161196657829003601f168201915b505050505089612e3b565b5b8015611a995750611a98600260008c73ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600101828154811015156119e857fe5b90600052602060002090600902016003018054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015611a8d5780601f10611a6257610100808354040283529160200191611a8d565b820191906000526020600020905b815481529060010190602001808311611a7057829003601f168201915b505050505088612e3b565b5b8015611ba35750611ba2600260008c73ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060010182815481101515611af257fe5b90600052602060002090600902016004018054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015611b975780601f10611b6c57610100808354040283529160200191611b97565b820191906000526020600020905b815481529060010190602001808311611b7a57829003601f168201915b505050505087612e3b565b5b8015611cad5750611cac600260008c73ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060010182815481101515611bfc57fe5b90600052602060002090600902016005018054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015611ca15780601f10611c7657610100808354040283529160200191611ca1565b820191906000526020600020905b815481529060010190602001808311611c8457829003601f168201915b505050505086612e3b565b5b15611cca57600181611cbf8c8461291f565b935093509350611ce4565b600181019050611736565b60008060008191509350935093505b5096509650969350505050565b600080600080611d11886020604051908101604052806000815250612e3b565b151515611d1d57600080fd5b611d2633610d72565b1515611d3157600080fd5b3388604051808373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166c0100000000000000000000000002815260140182805190602001908083835b602083101515611da95780518252602082019150602081019050602083039250611d84565b6001836020036101000a0380198251168184511680821785525050505050509050019250505060405180910390209350611de584888888612c9f565b1515611df057600080fd5b611e5c33896040518082805190602001908083835b602083101515611e2a5780518252602082019150602081019050602083039250611e05565b6001836020036101000a03801982511681845116808217855250505050505090500191505060405180910390206114f3565b809350819450829550505050821515611e7457600080fd5b8015611e7f57600080fd5b43600260003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060010183815481101515611ecf57fe5b9060005260206000209060090201600801819055506001600360108282829054906101000a900467ffffffffffffffff160192506101000a81548167ffffffffffffffff021916908367ffffffffffffffff1602179055505050505050505050565b6000611f3b612fca565b6000611f578e6020604051908101604052806000815250612e3b565b151515611f6357600080fd5b611f7d8d6020604051908101604052806000815250612e3b565b151515611f8957600080fd5b611fa38c6020604051908101604052806000815250612e3b565b151515611faf57600080fd5b611fc98b6020604051908101604052806000815250612e3b565b151515611fd557600080fd5b611fef8a6020604051908101604052806000815250612e3b565b151515611ffb57600080fd5b612015896020604051908101604052806000815250612e3b565b15151561202157600080fd5b87341015151561203057600080fd5b338e8e8e8e8e8e8e8e604051808a73ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166c0100000000000000000000000002815260140189805190602001908083835b6020831015156120af578051825260208201915060208101905060208303925061208a565b6001836020036101000a03801982511681845116808217855250505050505090500188805190602001908083835b60208310151561210257805182526020820191506020810190506020830392506120dd565b6001836020036101000a03801982511681845116808217855250505050505090500187805190602001908083835b6020831015156121555780518252602082019150602081019050602083039250612130565b6001836020036101000a03801982511681845116808217855250505050505090500186805190602001908083835b6020831015156121a85780518252602082019150602081019050602083039250612183565b6001836020036101000a03801982511681845116808217855250505050505090500185805190602001908083835b6020831015156121fb57805182526020820191506020810190506020830392506121d6565b6001836020036101000a03801982511681845116808217855250505050505090500184805190602001908083835b60208310151561224e5780518252602082019150602081019050602083039250612229565b6001836020036101000a03801982511681845116808217855250505050505090500183815260200182600019166000191681526020019950505050505050505050604051809103902092506122a583878787612c9f565b15156122b057600080fd5b6122b933610d72565b156124c6576122cc338e8e8e8e8e611717565b9050508091505080156122de57600080fd5b8d82600001819052508c82602001819052508b82604001819052508a8260600181905250898260800181905250888260a00181905250438260c0018181525050868260e001906000191690816000191681525050600082610100018181525050600260003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206001018054806001018281612392919061303e565b9160005260206000209060090201600084909190915060008201518160000190805190602001906123c4929190613070565b5060208201518160010190805190602001906123e1929190613070565b5060408201518160020190805190602001906123fe929190613070565b50606082015181600301908051906020019061241b929190613070565b506080820151816004019080519060200190612438929190613070565b5060a0820151816005019080519060200190612455929190613070565b5060c0820151816006015560e0820151816007019060001916905561010082015181600801555050506001600360088282829054906101000a900467ffffffffffffffff160192506101000a81548167ffffffffffffffff021916908367ffffffffffffffff160217905550612734565b43600260003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600001819055508d82600001819052508c82602001819052508b82604001819052508a8260600181905250898260800181905250888260a00181905250438260c0018181525050868260e001906000191690816000191681525050600082610100018181525050600260003373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060010180548060010182816125c1919061303e565b9160005260206000209060090201600084909190915060008201518160000190805190602001906125f3929190613070565b506020820151816001019080519060200190612610929190613070565b50604082015181600201908051906020019061262d929190613070565b50606082015181600301908051906020019061264a929190613070565b506080820151816004019080519060200190612667929190613070565b5060a0820151816005019080519060200190612684929190613070565b5060c0820151816006015560e0820151816007019060001916905561010082015181600801555050506001600360008282829054906101000a900467ffffffffffffffff160192506101000a81548167ffffffffffffffff021916908367ffffffffffffffff1602179055506001600360088282829054906101000a900467ffffffffffffffff160192506101000a81548167ffffffffffffffff021916908367ffffffffffffffff1602179055505b5050505050505050505050505050565b600360089054906101000a900467ffffffffffffffff1681565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b600360109054906101000a900467ffffffffffffffff1681565b6127a5612fb6565b6127ae82610d72565b15156127b957600080fd5b600260008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206001016001600260008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001908152602001600020600101805490500381548110151561285057fe5b90600052602060002090600902016000018054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156128f55780601f106128ca576101008083540402835291602001916128f5565b820191906000526020600020905b8154815290600101906020018083116128d857829003601f168201915b50505050509050919050565b60026020528060005260406000206000915090508060000154905081565b600061292a83610d72565b151561293557600080fd5b6000600260008573ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000206001018381548110151561298657fe5b90600052602060002090600902016008015411905092915050565b6129a9612fb6565b6000806129b585610d72565b15156129c057600080fd5b600260008673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060010184815481101515612a0f57fe5b9060005260206000209060090201600001600260008773ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060010185815481101515612a6f57fe5b906000526020600020906009020160060154600260008873ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060010186815481101515612ad057fe5b906000526020600020906009020160080154828054600181600116156101000203166002900480601f016020809104026020016040519081016040528092919081815260200182805460018160011615610100020316600290048015612b775780601f10612b4c57610100808354040283529160200191612b77565b820191906000526020600020905b815481529060010190602001808311612b5a57829003601f168201915b505050505092509250925092509250925092565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16141515612be657600080fd5b60003073ffffffffffffffffffffffffffffffffffffffff16311415612c0b57600080fd5b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166108fc3073ffffffffffffffffffffffffffffffffffffffff16319081150290604051600060405180830381858888f193505050501515612c8357600080fd5b565b600360009054906101000a900467ffffffffffffffff1681565b6000612ca96130f0565b60006040805190810160405280601c81526020017f19457468657265756d205369676e6564204d6573736167653a0a333200000000815250915081876040518083805190602001908083835b602083101515612d1a5780518252602082019150602081019050602083039250612cf5565b6001836020036101000a03801982511681845116808217855250505050505090500182600019166000191681526020019250505060405180910390209050600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16600182888888604051600081526020016040526000604051602001526040518085600019166000191681526020018460ff1660ff16815260200183600019166000191681526020018260001916600019168152602001945050505050602060405160208103908084039060008661646e5a03f11515612e0f57600080fd5b50506020604051035173ffffffffffffffffffffffffffffffffffffffff161492505050949350505050565b6000612e456130f0565b612e4d6130f0565b600085925084915081518351141515612e695760009350612fad565b60008351148015612e7b575060008251145b15612e895760019350612fad565b600090505b8251811015612fa8578181815181101515612ea557fe5b9060200101517f010000000000000000000000000000000000000000000000000000000000000090047f0100000000000000000000000000000000000000000000000000000000000000027effffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff19168382815181101515612f2057fe5b9060200101517f010000000000000000000000000000000000000000000000000000000000000090047f0100000000000000000000000000000000000000000000000000000000000000027effffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1916141515612f9d5760009350612fad565b600181019050612e8e565b600193505b50505092915050565b602060405190810160405280600081525090565b61012060405190810160405280612fdf613104565b8152602001612fec613104565b8152602001612ff9613104565b8152602001613006613104565b8152602001613013613104565b8152602001613020613104565b81526020016000815260200160008019168152602001600081525090565b81548183558181151161306b5760090281600902836000526020600020918201910161306a9190613118565b5b505050565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106130b157805160ff19168380011785556130df565b828001600101855582156130df579182015b828111156130de5782518255916020019190600101906130c3565b5b5090506130ec91906131af565b5090565b602060405190810160405280600081525090565b602060405190810160405280600081525090565b6131ac91905b808211156131a8576000808201600061313791906131d4565b60018201600061314791906131d4565b60028201600061315791906131d4565b60038201600061316791906131d4565b60048201600061317791906131d4565b60058201600061318791906131d4565b6006820160009055600782016000905560088201600090555060090161311e565b5090565b90565b6131d191905b808211156131cd5760008160009055506001016131b5565b5090565b90565b50805460018160011615610100020316600290046000825580601f106131fa5750613219565b601f01602090049060005260206000209081019061321891906131af565b5b505600a165627a7a72305820a0eb2bb88fea077cce771e97b64387ab9a8c6ba3f4fa7cd5360013086009f97e0029",
        "abi": [{"constant":true,"inputs":[],"name":"total_addresses","outputs":[{"name":"","type":"uint64"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"wallet","type":"address"}],"name":"user_last_used_name","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"wallet","type":"address"}],"name":"user_exists","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"wallet","type":"address"}],"name":"user_addresses_count","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"}],"name":"users","outputs":[{"name":"creation_block","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"wallet","type":"address"},{"name":"address_index","type":"uint256"}],"name":"user_address_confirmed","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"wallet","type":"address"},{"name":"creation_block","type":"uint256"}],"name":"user_address_by_creation_block","outputs":[{"name":"","type":"bool"},{"name":"","type":"uint256"},{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"data","type":"bytes32"},{"name":"v","type":"uint8"},{"name":"r","type":"bytes32"},{"name":"s","type":"bytes32"}],"name":"signer_is_valid","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"wallet","type":"address"},{"name":"country","type":"string"},{"name":"state","type":"string"},{"name":"city","type":"string"},{"name":"location","type":"string"},{"name":"zip","type":"string"}],"name":"user_address_by_address","outputs":[{"name":"","type":"bool"},{"name":"","type":"uint256"},{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"wallet","type":"address"},{"name":"address_index","type":"uint256"}],"name":"user_address","outputs":[{"name":"country","type":"string"},{"name":"state","type":"string"},{"name":"city","type":"string"},{"name":"location","type":"string"},{"name":"zip","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"signer","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"total_users","outputs":[{"name":"","type":"uint64"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"owner","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"total_confirmed","outputs":[{"name":"","type":"uint64"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"wallet","type":"address"},{"name":"address_index","type":"uint256"}],"name":"user_address_info","outputs":[{"name":"name","type":"string"},{"name":"creation_block","type":"uint256"},{"name":"confirmation_block","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"wallet","type":"address"},{"name":"confirmation_code_sha3","type":"bytes32"}],"name":"user_address_by_confirmation_code","outputs":[{"name":"","type":"bool"},{"name":"","type":"uint256"},{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"confirmation_code_plain","type":"string"},{"name":"sig_v","type":"uint8"},{"name":"sig_r","type":"bytes32"},{"name":"sig_s","type":"bytes32"}],"name":"confirm_address","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"amount_wei","type":"uint256"}],"name":"withdraw_some","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"name","type":"string"},{"name":"country","type":"string"},{"name":"state","type":"string"},{"name":"city","type":"string"},{"name":"location","type":"string"},{"name":"zip","type":"string"},{"name":"price_wei","type":"uint256"},{"name":"confirmation_code_sha3","type":"bytes32"},{"name":"sig_v","type":"uint8"},{"name":"sig_r","type":"bytes32"},{"name":"sig_s","type":"bytes32"}],"name":"register_address","outputs":[],"payable":true,"stateMutability":"payable","type":"function"},{"constant":false,"inputs":[{"name":"new_signer","type":"address"}],"name":"set_signer","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[],"name":"withdraw_all","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor"}]
    }
}
</pre>
</details>
