### ISSUE TITLE
(Improvement) Fix data in config private example

### ISSUE THREAD

**Issue by phahulin** [poanetwork/poa-popa#110]
- **What is it?** (leave one option)
   * `(Improvement)` proposal (i.e. some existing feature can be improved)

- **What problem have you encountered (provide steps to reproduce if possible) / What feature are you talking about?**
This file is mentioned in readme
https://github.com/poanetwork/poa-popa/blob/master/web-dapp/server-config-private.example.js

however, `lobApiVersion` should be `2017-06-16`
also, `popaContractAddress` is probably unnecessary? (set in `.env` and I couldn't find this variable being used in code)

**Comment by fvictorio** [comment]
The `lobApiVersion` depends on the version of your LOB API key. Since that it's just an example, I think any value is OK (as long as it has the right format).

You are right about `popaContractAddress`, I think I added it accidentally.

**Comment by phahulin** [comment]
You're right about the API key, mine is just too old
