### ISSUE TITLE
(Feature) Limit number of postcards sent per day

### ISSUE THREAD

**Issue by phahulin** [poanetwork/poa-popa#115]
- **What is it?** (leave one option)
    * New `(Feature)` request (i.e. some nice-to-have feature is missing)

- **What problem have you encountered (provide steps to reproduce if possible) / What feature are you talking about?**
To prevent hackery and misuse, I suggest we add an option to limit the number of postcards that can be sent per day. Since primary use-case of this dapp is to verify addresses of poa network validators, even a low limit (~10) should not impose any hardship.

- **What is expected behavior / What is proposed feature?**
1. add a configuration option to limit number of postcards that can be sent per 24 hours 
2. current state should be stored in database
3. when calling `createPostcard` it should be checked if limit is not exceeded, before actually calling lob api
4. when user presses `ORDER` and calls `/prepareRegTx` it should be checked that limit is not exceeded yet. Error message should be displayed if it is
5. other functionality (verifying postcards, removing addresses) should still be available

@igorbarinov @pablofullana what do you think?

**Comment by igorbarinov** [comment]
@phahulin I agree, adding limitations and thresholds is always good
