### ISSUE TITLE
Event log is beneficial to the observation of setting variables

### ISSUE THREAD

**Issue by pablofullana** [poanetwork/poa-popa#125]
**Observation:** When calling setSigner() with a new signer address, it is highly recommended that you emit an event to log the execution. This is not standard behavior, though it helps you track the history and lets you notice the variable has been changed. Similar functions are listed below: setRegistry(), registerAddress(), unregisterAddress()

**Comment by phahulin** [comment]
Let's also add an event for `confirmAddress()`. @pablofullana what do you think? Then we'll have a complete lifecycle reflected in events

**Comment by pablofullana** [comment]
Indeed, sounds logical to have that one as well. @fvictorio any thoughts against this?

**Comment by fvictorio** [comment]
No, that makes sense :+1:
