### ISSUE TITLE
Add audit report

### ISSUE THREAD

**Issue by pablofullana** [poanetwork/poa-popa#132]
Add audit report PDF file to repository

**Comment by phahulin** [comment]
Here are Markdown files of the report: https://github.com/poanetwork/poa-popa/pull/142

**Comment by fvictorio** [comment]
#142 was merged. Should we close this?

**Comment by pablofullana** [comment]
[Poa PoPA Audit Report FINAL.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58dbaada572686001a5bb236/125516c66e82c728ace21e0d46d89b9b63b28c99aea99e56a054e4d41b43377c3b10e30d59abc204fd0e39111d0014f9121c4d4eeefcd82cafe76e72de0802bcd33f0b74c63f14f9ebd44cee57a83c990dd4e8e8d51199a26867f5819d4e3914041d8bf85c33a59b42ce5bff49f300.pdf)
