### ISSUE TITLE
(Refactor) change address removal method

### ISSUE THREAD

**Issue by phahulin** [poanetwork/poa-popa#149]
- **What is it?** (leave one option)
    * `(Refactor)` proposal (i.e. no new features or updates, just code optimization/library updates)

https://github.com/poanetwork/poa-popa/blob/master/blockchain/contracts/ProofOfPhysicalAddress.sol#L341

In current implementation when address is removed by a user, elements of `physicalAddresses` array are shifted and then the last element is deleted:
```
[0, 1, 2, 3, 4] --> remove 2 --> [0, 1, 3, 4, 4] --> [0, 1, 3, 4]
```
Suggestion is to copy the last element of array to the place of the removed element, then delete the last element:
```
[0, 1, 2, 3, 4] --> remove 2 --> [0, 1, 4, 3, 4] --> [0, 1, 4, 3]
```
(this is for the case when removed element is not already the last one)

This method requires fewer operations and hence less gas, however the order of elements is not preserved. But it doesn't seem to be important, since they can be ordered by creation block anyway.
 
@fvictorio @matiasgaratortiz what do you think?

**Comment by fvictorio** [comment]
Sounds good! I don't think the order of elements is important. I'll implement it.
