### ISSUE TITLE
Audit #2

### ISSUE THREAD

**Issue by pablofullana** [poanetwork/poa-popa#162]
- [x] Parent of #133
- [x] Parent of #134
- [x] Parent of #135
- [x] Parent of #145
- [x] Parent of #146
- [x] Parent of #147
- [x] Parent of #148
- [x] Parent of #149
- [x] Parent of #150
- [x] Parent of #157

- [x] Parent of #164
- [x] Parent of  #165
- [x] Parent of  #166
- [x] Parent of  #167
- [x] Parent of  #168 
- [x] **Parent of**  #169 (should be fixed, but awaiting auditors' approval)
- [x] Parent of  #170
- [ ] Parent of  #187

More issues to be created as we keep getting audit feedback

**Comment by phahulin** [comment]
Server-side audit results (part I) ^
