### ISSUE TITLE
(Improvement) UI Enhancement and suggestions

### ISSUE THREAD

**Issue by SiddigZeidan** [poanetwork/poa-popa#175]
- Logo looks blurry. Needs a retina version 
![image](https://user-images.githubusercontent.com/4807398/40941856-48a11698-681a-11e8-8d02-97664a215d7d.png)

- The box-shadow on the hover button is too thick. I'd recommend changing to `box-shadow: inset 0 0 0 1px #5c34a2;` while look like the screenshot below  
![image](https://user-images.githubusercontent.com/4807398/40941976-af60e796-681a-11e8-9ef1-da710a9c20c7.png)

- Bold the `how-to-title` titles on 
![image](https://user-images.githubusercontent.com/4807398/40942291-c0fb43d8-681b-11e8-9b46-db26665c7106.png)

- Change 0.04 ETH to 0.04 POA
![image](https://user-images.githubusercontent.com/4807398/40942315-d17fd656-681b-11e8-9dd5-a6faf947b971.png)

- When I click "Continue" there is no refresh and the URL changes to the next page in a smooth manner. This is not the case when I click "Back" as it seems to refresh the page

- Country should be disabled or read-only 
![image](https://user-images.githubusercontent.com/4807398/40942548-9665f64e-681c-11e8-86d2-5d05e2da2a3c.png)

- All US armed forces should be at the bottom and should be together
![image](https://user-images.githubusercontent.com/4807398/40942584-ab63e312-681c-11e8-8af3-e0d5428b479a.png)

**Comment by igorbarinov** [comment]
Change to 0.04 POA on POA

It's a good question about a different price for diff networks
@pablofullana do we have an issue for that?

**Comment by pablofullana** [comment]
No we don't. This would be required for PoPA as well, correct?

**Comment by igorbarinov** [comment]
I think it should be in config for each chain on all proof of apps

**Comment by phahulin** [comment]
We have [`priceWei` option in server-config](https://github.com/poanetwork/poa-popa/blob/master/web-dapp/server-config.js#L29), so we need to "forward" it to UI.

I'd like to point out that in the current implementation server can only support working with a single network, so we'll need to have multiple instances, one per chain, if that is required.
The currently deployed version at popa....network works with Core.

**Comment by igorbarinov** [comment]
Sounds good. Let's point UI to config
and specify 1 POA for verification
