### ISSUE TITLE
(Improvement) Displaying postcard price in UI

### ISSUE THREAD

**Issue by phahulin** [poanetwork/poa-popa#177]
- **What is it?** (leave one option)
    * `(Improvement)` proposal (i.e. some existing feature can be improved)

- **What problem have you encountered (provide steps to reproduce if possible) / What feature are you talking about?**

In the current implementation price tag is hard-coded in the UI, it should be set via a config file.

- **What is expected behaviour / What is proposed feature?**
1. Server already has `priceWei` option in server-config, we should use it to display price in the UI (but not in wei). It would also be good to add a new option that specifies name of the coin (e.g. `priceSymbol: 'POA'`)
Since UI is handled by react, we can't directly use `priceWei` from config, maybe we can add this to [server-config](https://github.com/poanetwork/poa-popa/blob/master/web-dapp/server-config.js):
```
process.env.REACT_APP_PRICE = web3.fromWei(web3.toBigNumber(cfg.priceWei), 'eth');
process.env.REACT_APP_PRICE_SYMBOL = web3.priceSymbol
```
If it doesn't work this way, we'll have to add them to `.env` directly.

2. Change default value from `0.04e+18` to `1e+18`

**Comment by pablofullana** [comment]
Request comes from #175
