### ISSUE TITLE
(Question) Why are license notices different in package.json and LICENSE?

### ISSUE THREAD

**Issue by syuhei176** [poanetwork/poa-popa#194]
- **What is it?** (leave one option)

Hi there.
I just want know.
Why are license notices different in package.json and LICENSE?

https://github.com/poanetwork/poa-popa/blob/master/package.json#L5
https://github.com/poanetwork/poa-popa/blob/master/LICENSE

**Comment by phahulin** [comment]
Hi @syuhei176 it's by mistake, the one in license file is the correct one. We'll update `package.json` to reference `LICENSE`. Thanks for noting this!
