### ISSUE TITLE
(Feature) Add Coverage badge

### ISSUE THREAD

**Issue by pablofullana** [poanetwork/poa-popa#29]
- **What is it?** (leave one option)
    * New `(Feature)` request (i.e. some nice-to-have feature is missing)

- **What problem have you encountered (provide steps to reproduce if possible) / What feature are you talking about?**
Add a coverage badge to the README file, making it easier to see.

- **What is expected behaviour / What is proposed feature?**
Coverage badge in README

- **Additional information**
We need to active the repository on [Coveralls]https://coveralls.io/github/poanetwork/poa-popa) and [Travis](https://travis-ci.org/poanetwork/poa-popa)

[x]  [Coveralls](https://coveralls.io/github/poanetwork/poa-popa)
[]  [Travis](https://travis-ci.org/poanetwork/poa-popa)

**Comment by phahulin** [comment]
Should be activated on travis now

**Comment by igorbarinov** [comment]
@pablofullana please elaborate on coveralls 
We didn't use it before. what is the purpose of it?

**Comment by pablofullana** [comment]
@igorbarinov @matiasgaratortiz added the integration with coveralls.io so we have insights on code coverage. This will allow us to rely on our testing suite with more confidence and put special focus on parts of the code that are not fully tested.

**Comment by igorbarinov** [comment]
I see. @pablofullana  Do you need anything from me or Pavel for it?

**Comment by pablofullana** [comment]
@igorbarinov we are working on this right now. We'll let you guys know if anything is required from your side.
