### ISSUE TITLE
(Feature) support multiple networks

### ISSUE THREAD

**Issue by phahulin** [poanetwork/poa-popa#52]
- **What is it?** (leave one option)
    * New `(Feature)` request (i.e. some nice-to-have feature is missing)

- **What problem have you encountered (provide steps to reproduce if possible) / What feature are you talking about?**
1. there is no check if contract is deployed or not on the current network (the one user is connected to via MetaMask)
2. single instance of the web app should support multiple networks (different contract addresses)

- **What is expected behaviour / What is proposed feature?**
1. check if contract is deployed to the current network. if not - display error message and block any other elements of dapp
2. get `netId` from client-side, send it to server along with wallet and other parameters. Redefine structure of contract_output.json so that it would store a dict `netId -> contract_address` (abi is the same). Server should be able to keep and array of web3 instances and contracts for each network, and use correct one when fetching address details.

**Comment by fvictorio** [comment]
This seems to be implemented. Can we close the issue?

**Comment by phahulin** [comment]
This is not implemented yet, but low priority (for the future)

**Comment by fvictorio** [comment]
@phahulin Is this still on the roadmap or we can close the issue?

**Comment by phahulin** [comment]
There are no plans for it, so I think it can be closed
