### ISSUE TITLE
Addresses considered in functions that not necessarily should

### ISSUE THREAD

**Issue by Janther** [poanetwork/poa-popa#78]
- **What is it?** (leave one option)
    * `(Bug)` report (i.e. something doesn't work as it should)

- **What problem have you encountered (provide steps to reproduce if possible) / What feature are you talking about?**

The function [user_last_used_name](https://github.com/poanetwork/poa-popa/blob/master/blockchain/contracts/ProofOfPhysicalAddress.sol#L165) returns the last name submited regardless of it being confirmed.

The function [user_addresses_count](https://github.com/poanetwork/poa-popa/blob/master/blockchain/contracts/ProofOfPhysicalAddress.sol#L173) also considers unconfirmed addresses.

- **What is expected behaviour**

Only consider confirmed addresses.

**Comment by phahulin** [comment]
These functions are not currently used by the DApp, they can be regarded as helper functions for the future if we'll support a more advanced UI (list of confirmed addresses, etc).

We can either remove them for now from the contract or create two variants of each function:
```
user_last_used_name -> user_last_confirmed_name + user_last_submitted_name
user_addresses_count -> user_confirmed_addresses_count + user_total_addresses_count
```
