### ISSUE TITLE
(Discussion) Let's only store the keccak of the address on chain

### ISSUE THREAD

**Issue by Janther** [poanetwork/poa-popa#90]
I want to propose to only store on chain the keccak and confirmation codes on the contract.
and have the ERC780 registry store information regarding blocknumber of confirmation or if it has been requested to reconfirm.

The owner of the ethereum address can tell anyone what is his phisical address and have the `ProofOfPhysicalAddress.sol` just validate with a true or false.

**Comment by phahulin** [comment]
Based on https://github.com/poanetwork/poa-popa/issues/85#issuecomment-375297422 we're not building a general-purpose app now, but a validator-specific one, so their addresses should be kept public on-chain.
